config/routes.rb
::Refinery::Application.routes.draw do
  # resources :variants, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :variants, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/variant.rb
class Variant < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :stock_code]

  validates :name, :presence => true
  
  belongs_to :image
  belongs_to :product
  has_many :line_items
  
  delegate :url, :to => :image, :prefix => true
  
  def name_and_price
    name + " - R" + price.to_i.to_s
  end
end

app/controllers/admin/variants_controller.rb
module Admin
  class VariantsController < Admin::BaseController

    crudify :variant,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/views/admin/variants/_actions.html.erb
<ul>
  <% if Admin::VariantsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_variants_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_variant_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::VariantsController.sortable? and Variant.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Variants"),
                 admin_variants_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Variants"),
                 admin_variants_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/variants/_form.html.erb
<%= form_for [:admin, @variant] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @variant,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>

  <div class='field'>
    <%= f.label :product_id -%>
	<%= f.collection_select :product_id, Product.order(:name), :id, :name, :prompt => "-- Select --"  -%>		
  </div>
  
  <div class='field'>
    <%= f.label :image -%>
    <%= render :partial => "/shared/admin/image_picker", :locals => {
          :f => f,
          :field => :image_id,
          :image => @variant.image,
          :toggle_image_display => false
        } %>
  </div>
  
  <div class='field'>
    <%= f.label :price -%>
    <%= f.text_field :price  -%>
  </div>
  
  <div class='field'>
    <%= f.label :stock_code -%>
    <%= f.text_field :stock_code  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.variants.variant'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @variant.name)
              } %>
<% end -%>

app/views/admin/variants/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @variants.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'variants' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/variants/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'variant', :collection => @variants %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/variants/_variant.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(variant) -%>">
  <span class='title'>
    <%= variant.name %>
    <span class="preview"><%= variant.product.name %></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_variant_path(variant),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_variant_path(variant),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => variant.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/variants/_variants.html.erb
<%= will_paginate @variants %>
<%= render :partial => "sortable_list" %>

app/views/admin/variants/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/variants/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::VariantsController.sortable? and Variant.count > 1 %>

app/views/admin/variants/new.html.erb
<%= render :partial => "form" %>